--- #YAML:1.0
name:                Apache-DBI
version:             1.05
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    DBI:                           1
    Digest::MD5:                   2.2
    Digest::SHA1:                  2.01
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
