---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Apache-DBI
no_index:
  directory:
    - t
    - inc
requires:
  DBI: 1
  Digest::MD5: 2.2
  Digest::SHA1: 2.01
  Test::More: 0
version: 1.12
